### ISSUE TITLE
Crash when upgrading from Vanillatools-1.12-1.0.7b to Current ToolTweaks 1.0.7

### ISSUE THREAD

**Issue by titanium-cid** [SirWindfield/vanilla-tools#14]
As the subject says, I am having issue when I update to Tooltweaks 1.0.7 from the older Vanillatools which results in the following crash - https://pastebin.com/NPDALWrW

Unfortunately this is stopping me updating my pack on Twitch, as the older file is no longer available.

Any help appreciated 

Cid

[crash-2018-02-04_18.46.42-client.txt](https://github.com/SirWindfield/tooltweaks/files/1693196/crash-2018-02-04_18.46.42-client.txt)

**Comment by fangedhex** [comment]
I will ask @SirWindfield , he made some change recently so maybe he has more idea to fix than me :P

**Comment by mainrs** [comment]
Ok, looks like [Shadowfact's Forgelin](https://minecraft.curseforge.com/projects/shadowfacts-forgelin) is not installed. Since I moved the source code from Java to Kotlin (as I just like kotlin more since I started using it within my own Android apps), you need to have it installed as a mod too. Curseforge should actually install it automatically when you download ToolTweaks using the Twitch App. If you download it manually, make sure to add the mod too! 

I tried to replicate it with just installing ToolTweaks and it works on my instance with the same jar that I uploaded to Curseforge.

**Please report back if this fixes your issue!**

**Comment by titanium-cid** [comment]
Absolutely fixed it, thanks. I missed the Forgelin when I moved the pack from Twitch to MultiMC. It may be worth noting that dependency on the curseforge page though.

Thanks for the prompt response.

**Comment by mainrs** [comment]
I added an entry to the summary page! No problem. Feel free to open up other issues if you have any problems!
